import AdminProtected from "@/components/adminComponent/AdminProtected";
import AdminSitebar from "@/components/adminComponent/AdminSitebar";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-4 gap-4  bg-primary bg-opacity-10">
          <div className="col-span-1">
            <AdminSitebar />
          </div>
          <div className="col-span-3 px-4">
            {/* <AdminProtected>{children}</AdminProtected> */}
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
