import PageLayout from "@/components/utils/PageLayout";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-orange-100 bg-opacity-50">
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
}
